export const CARD_DUMMY_DATA = [
{
    title: '보람찬 하루',
    nickname: '원우형',
    cardImage: '',
    avatarImage: '',
    isPublic: false,
    updateDate: '2024-04-17',
    hits: 76,
    summary:
    '오늘 하루 전체적으로 보람찼다. 이유는 오늘 벚꽃이 아름답기 때문이었다.',
},
{
    title: '보람찬 하루',
    nickname: '원우형',
    cardImage: '',
    avatarImage: '',
    isPublic: false,
    updateDate: '2024-04-17',
    hits: 76,
    summary: '오늘 하루 전체적으로 보람찼다. 이유는 ...',
},
{
    title: '보람찬 하루',
    nickname: '원우형',
    cardImage: '',
    avatarImage: '',
    isPublic: false,
    updateDate: '2024-04-17',
    hits: 76,
    summary: '오늘 하루 전체적으로 보람찼다. 이유는 ...',
},
{
    title: '보람찬 하루',
    nickname: '원우형',
    cardImage: '',
    avatarImage: '',
    isPublic: false,
    updateDate: '2024-04-17',
    hits: 76,
    summary: '오늘 하루 전체적으로 보람찼다. 이유는 ...',
},
{
    title: '보람찬 하루',
    nickname: '원우형',
    cardImage: '',
    avatarImage: '',
    isPublic: false,
    updateDate: '2024-04-17',
    hits: 76,
    summary: '오늘 하루 전체적으로 보람찼다. 이유는 ...',
},
]